name: Continuous Deployment (Prod)
on:
  push:
    branches: [ production ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: suzalshrestha/test:${{ github.sha }}

      - name: Clone staging-ops repo, update, and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/SuzalShrestha/argo-deployment
          cd argo-deployment
          sed -i 's|image: suzalshrestha/test:.*|image: suzalshrestha/test:${{ github.sha }}|' manifest.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add argo-deployment/manifest.yml
          git commit -m "Update test image to ${{ github.sha }}"
          git push https://${PAT}@github.com/SuzalShrestha/argo-deployment.git main